version: 0.2

phases:
  install:
    commands:
      - echo "Preparing static files from root directory"
      - echo "Current directory:"
      - pwd
      - echo "Directory contents:"
      - ls -la

  build:
    commands:
      - echo "No build step required"

artifacts:
  base-directory: .
  files:
    - '**/*'
