name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', depending on your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Change if your site files are in a subfolder like 'dist/'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
